cd /Users/tom/github/ml_infn_hackBase
cp virgo.ipynb VM_COLLABSHARED/GW/
cp virgo.ipynb VM_BACKUP/VM_COLLABSHARED/GW/
cp btaggingTom_May26_nocelloutput* VM_COLLABSHARED/HEP/
cp btaggingTom_May26_nocelloutput* VM_BACKUP/VM_COLLABSHARED/HEP/
cp DL_classification_mammocalcification_0106.ipynb DL_classification_mammocalcification_STUDENT.ipynb VM_COLLABSHARED/FISMED/
cp DL_classification_mammocalcification_0106.ipynb DL_classification_mammocalcification_STUDENT.ipynb VM_BACKUP/VM_COLLABSHARED/FISMED/

